server:
  port: ${PORT:8701} #服务端口
  tomcat:
    accept-count: 1200
    max-connections: 1000
    max-threads: 1000
    min-spare-threads: 100

spring:
  application:
    name: baas-service #指定服务名
  profiles:
    active: ${ENV:uat}
  jackson:
    serialization:
      write-dates-as-timestamps: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
